name: GFSLT-VLP
data:
  train_label_path: ./data/how2sign/labels.train
  dev_label_path: ./data/how2sign/labels.dev
  test_label_path: ./data/how2sign/labels.test
  img_path: ./data/how2sign/
  max_length: 300
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  tokenizer: /root/autodl-tmp/GFSLT-VLP-main/pretrain_models/MBart_trimmed
  transformer: /root/autodl-tmp/GFSLT-VLP-main/pretrain_models/MBart_trimmed
  visual_encoder: /root/autodl-tmp/GFSLT-VLP-main/pretrain_models/mytran
  sign_proj: True
