name: GFSLT-VLP
data:
  train_label_path: F:\test_train\how2sign\labels.train
  dev_label_path: F:\test_train\how2sign\labels.dev
  test_label_path: F:\test_train\how2sign\labels.test
  img_path: F:\test_train\how2sign\frame\
  max_length: 500
  "keypoint_path": F:\test_train\how2sign\frame\
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  tokenizer: D:\VK-S2T\pretrain_models\MBart_trimmed
  transformer: D:\VK-S2T\pretrain_models\MBart_trimmed
  visual_encoder: D:\VK-S2T\pretrain_models\mytran
  sign_proj: True
